# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: earthquake-tracker
language: python
runtimeConfig:
  start:
    - fastapi run
database:
  hostname: localhost
  port: 5432
  username: postgres
  password: ${PGPASSWORD}
  app_db_name: earthquake_tracker
  migrate:
    - alembic upgrade head
telemetry:
  logs:
    logLevel: INFO