# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact/main/dbos-config.schema.json

database:
  migrate: ['npx knex migrate:latest','npx knex seed:run']
runtimeConfig:
  start:
    - npm run start
application:
  # Local defaults
  payment_host: 'http://localhost:8086'
  local_host: 'http://localhost:8082'
  # cloud example
  # payment_host: 'https://<username>-payment-backend.cloud.dbos.dev'
  # local_host: 'https://<username>-shop-backend.cloud.dbos.dev'

