/**
 * bank-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ListTxnForAccountFunc200ResponseInner { 
    /**
     * bigint
     */
    txnId: number;
    /**
     * bigint
     */
    fromAccountId: number;
    fromLocation: string;
    /**
     * bigint
     */
    toAccountId: number;
    toLocation: string;
    amount: number;
    timestamp: string;
}

