# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-sdk/main/dbos-config.schema.json

database:
  hostname: 'localhost'
  port: 5432
  username: 'postgres'
  password: ${PGPASSWORD}
  app_db_name: 'shop'
  user_database: 'shop' # Will be deprecated, use app_db_name instead
  connectionTimeoutMillis: 3000
  app_db_client: 'knex'
  user_dbclient: 'knex' # Will be deprecated, use app_db_client instead
  migrate: ['npx knex migrate:latest','npx knex seed:run']
  rollback: ['npx knex migrate:rollback']
runtimeConfig:
  port: 8082
application:
  payment_host: 'http://localhost:8086'
  local_host: 'http://localhost:8082'
  # cloud example
  # payment_host: 'https://dbos_domain/dbos-testuser/application/payment-backend'
  # local_host: 'https://dbos_domain/dbos-testuser/application/shop-backend'
  
