database:
  hostname: 'localhost'
  port: 5432
  username: 'postgres'
  password: ${PGPASSWORD}
  user_database: 'shop'
  system_database: 'shop_systemdb'
  connectionTimeoutMillis: 3000
  user_dbclient: 'knex'
  ssl_ca: us-east-1-bundle.pem
  migrate: ['migrate:latest','seed:run']
  rollback: ['migrate:rollback']
runtimeConfig:
  port: 8082
application:
  payment_host: 'https://mj.cloud.dbos.dev/dbos-testuser/application/payment-backend'
  local_host: 'https://mj.cloud.dbos.dev/dbos-testuser/application/shop-backend'
