database:
  hostname: 'localhost'
  port: 5432
  username: 'postgres'
  password: ${PGPASSWORD}
  user_database: 'shop'
  system_database: 'shop_systemdb'
  connectionTimeoutMillis: 3000
  user_dbclient: 'knex'
runtimeConfig:
  port: 8082
application:
  payment_host: 'http://localhost:8086'
  local_host: 'http://localhost:8082'

