database:
  hostname: 'localhost'
  port: 5432
  connectionTimeoutMillis: 3000
  username: ${PGUSER}
  app_db_name: ${PGDATABASE}
  password: ${PGPASSWORD}
  app_db_client: "prisma"
  migrate:
    - node generate_env.js && npx prisma migrate deploy
runtimeConfig:
  start:
    - npm run start
