# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: widget-store
language: python
database_url: ${DBOS_DATABASE_URL}
runtimeConfig:
  start:
    - python3 -m widget_store.main
database:
  migrate:
    - alembic upgrade head
    - python3 -m migrations.reset_database