# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: widget-store
language: python
runtimeConfig:
  start:
    - fastapi run widget_store/main.py
database_url: ${DBOS_DATABASE_URL}
database:
  migrate:
    - alembic upgrade head
    - python3 -m migrations.reset_database
telemetry:
  logs:
    logLevel: INFO