# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: widget-store
language: python
runtimeConfig:
  start:
    - fastapi run widget_store/main.py
database:
  hostname: localhost
  port: 5432
  username: postgres
  password: ${PGPASSWORD}
  migrate:
    - alembic upgrade head
    - python3 -m migrations.reset_database
telemetry:
  logs:
    logLevel: INFO