[project]
name = "widget-store"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "alembic>=1.16.5",
    "dbos[otel]==1.15.0a7",
    "fastapi[standard]>=0.117.1",
]
