/* tslint:disable */
/* eslint-disable */
/**
 * bank-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ListTxnForAccountFunc200ResponseInner } from './ListTxnForAccountFunc200ResponseInner';
import {
    ListTxnForAccountFunc200ResponseInnerFromJSON,
    ListTxnForAccountFunc200ResponseInnerFromJSONTyped,
    ListTxnForAccountFunc200ResponseInnerToJSON,
} from './ListTxnForAccountFunc200ResponseInner';

/**
 * 
 * @export
 * @interface DepositRequest
 */
export interface DepositRequest {
    /**
     * 
     * @type {ListTxnForAccountFunc200ResponseInner}
     * @memberof DepositRequest
     */
    history: ListTxnForAccountFunc200ResponseInner;
}

/**
 * Check if a given object implements the DepositRequest interface.
 */
export function instanceOfDepositRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "history" in value;

    return isInstance;
}

export function DepositRequestFromJSON(json: any): DepositRequest {
    return DepositRequestFromJSONTyped(json, false);
}

export function DepositRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepositRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'history': ListTxnForAccountFunc200ResponseInnerFromJSON(json['history']),
    };
}

export function DepositRequestToJSON(value?: DepositRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'history': ListTxnForAccountFunc200ResponseInnerToJSON(value.history),
    };
}

