/* tslint:disable */
/* eslint-disable */
/**
 * bank-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Greeting200Response
 */
export interface Greeting200Response {
    /**
     * 
     * @type {string}
     * @memberof Greeting200Response
     */
    msg: string;
}

/**
 * Check if a given object implements the Greeting200Response interface.
 */
export function instanceOfGreeting200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "msg" in value;

    return isInstance;
}

export function Greeting200ResponseFromJSON(json: any): Greeting200Response {
    return Greeting200ResponseFromJSONTyped(json, false);
}

export function Greeting200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Greeting200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'msg': json['msg'],
    };
}

export function Greeting200ResponseToJSON(value?: Greeting200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'msg': value.msg,
    };
}

