# OpenApi specification generated for application

openapi: 3.0.3
info:
  title: payment-backend
  version: 0.0.1
paths:
  /api/create_payment_session:
    post:
      operationId: createPaymentSession
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
                required:
                  - session_id
                  - url
                  - payment_status
                properties:
                  session_id:
                    type: string
                  url:
                    type: string
                  payment_status:
                    type: string
                    enum:
                      - pending
                      - paid
                      - cancelled
                additionalProperties: false
      parameters:
        - $ref: "#/components/parameters/dbosWorkflowUUID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                webhook:
                  type: string
                success_url:
                  type: string
                cancel_url:
                  type: string
                items:
                  type: array
                  items:
                    $ref: "#/components/schemas/PaymentItem"
                client_reference_id:
                  type: string
              required:
                - webhook
                - success_url
                - cancel_url
                - items
  /api/session/{session_id}:
    get:
      operationId: retrievePaymentSession
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
                required:
                  - session_id
                  - url
                  - payment_status
                properties:
                  session_id:
                    type: string
                  url:
                    type: string
                  payment_status:
                    type: string
                    enum:
                      - pending
                      - paid
                      - cancelled
                additionalProperties: false
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/dbosWorkflowUUID"
  /api/session_info/{session_id}:
    get:
      operationId: getSessionInformation
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
                required:
                  - session_id
                  - success_url
                  - cancel_url
                  - items
                properties:
                  session_id:
                    type: string
                  success_url:
                    type: string
                  cancel_url:
                    type: string
                  status:
                    type: string
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/PaymentItem"
                additionalProperties: false
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/dbosWorkflowUUID"
  /api/submit_payment:
    post:
      operationId: submitPayment
      responses:
        "204":
          description: No Content
      parameters:
        - $ref: "#/components/parameters/dbosWorkflowUUID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
              required:
                - session_id
  /api/cancel_payment:
    post:
      operationId: cancelPayment
      responses:
        "204":
          description: No Content
      parameters:
        - $ref: "#/components/parameters/dbosWorkflowUUID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
              required:
                - session_id
components:
  parameters:
    dbosWorkflowUUID:
      name: dbos-workflowuuid
      in: header
      required: false
      description: Caller specified [workflow idempotency
        key](https://docs.dbos.dev/tutorials/idempotency-tutorial#setting-idempotency-keys)
      schema:
        type: string
  schemas:
    PaymentItem:
      type: object
      required:
        - description
        - price
        - quantity
      properties:
        description:
          type: string
        price:
          type: number
        quantity:
          type: number
      additionalProperties: false
  securitySchemes: {}
