/* tslint:disable */
/* eslint-disable */
/**
 * operon-demo-shop-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddToCartRequest
 */
export interface AddToCartRequest {
    /**
     * 
     * @type {string}
     * @memberof AddToCartRequest
     */
    username: string;
    /**
     * 
     * @type {number}
     * @memberof AddToCartRequest
     */
    productId: number;
}

/**
 * Check if a given object implements the AddToCartRequest interface.
 */
export function instanceOfAddToCartRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "productId" in value;

    return isInstance;
}

export function AddToCartRequestFromJSON(json: any): AddToCartRequest {
    return AddToCartRequestFromJSONTyped(json, false);
}

export function AddToCartRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddToCartRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'productId': json['product_id'],
    };
}

export function AddToCartRequestToJSON(value?: AddToCartRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'product_id': value.productId,
    };
}

