/* tslint:disable */
/* eslint-disable */
/**
 * operon-demo-shop-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCartRequest
 */
export interface GetCartRequest {
    /**
     * 
     * @type {string}
     * @memberof GetCartRequest
     */
    username: string;
}

/**
 * Check if a given object implements the GetCartRequest interface.
 */
export function instanceOfGetCartRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function GetCartRequestFromJSON(json: any): GetCartRequest {
    return GetCartRequestFromJSONTyped(json, false);
}

export function GetCartRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCartRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
    };
}

export function GetCartRequestToJSON(value?: GetCartRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
    };
}

