/* tslint:disable */
/* eslint-disable */
/**
 * operon-demo-shop-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProducts200ResponseInner
 */
export interface GetProducts200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof GetProducts200ResponseInner
     */
    displayPrice: string;
    /**
     * 
     * @type {number}
     * @memberof GetProducts200ResponseInner
     */
    productId: number;
    /**
     * 
     * @type {string}
     * @memberof GetProducts200ResponseInner
     */
    product: string;
    /**
     * 
     * @type {string}
     * @memberof GetProducts200ResponseInner
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof GetProducts200ResponseInner
     */
    imageName: string;
    /**
     * 
     * @type {number}
     * @memberof GetProducts200ResponseInner
     */
    price: number;
}

/**
 * Check if a given object implements the GetProducts200ResponseInner interface.
 */
export function instanceOfGetProducts200ResponseInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "displayPrice" in value;
    isInstance = isInstance && "productId" in value;
    isInstance = isInstance && "product" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "imageName" in value;
    isInstance = isInstance && "price" in value;

    return isInstance;
}

export function GetProducts200ResponseInnerFromJSON(json: any): GetProducts200ResponseInner {
    return GetProducts200ResponseInnerFromJSONTyped(json, false);
}

export function GetProducts200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProducts200ResponseInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'displayPrice': json['display_price'],
        'productId': json['product_id'],
        'product': json['product'],
        'description': json['description'],
        'imageName': json['image_name'],
        'price': json['price'],
    };
}

export function GetProducts200ResponseInnerToJSON(value?: GetProducts200ResponseInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'display_price': value.displayPrice,
        'product_id': value.productId,
        'product': value.product,
        'description': value.description,
        'image_name': value.imageName,
        'price': value.price,
    };
}

