# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact/main/dbos-config.schema.json

database:
  migrate: ['npx knex migrate:latest']
runtimeConfig:
  start:
    - npm run start
application:
  frontend_host: 'http://localhost:8086'
  # For DBOS Cloud:
  #frontend_host: 'https://<username>-shop-backend.cloud.dbos.dev'
