/**
 * Operon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentItem } from './paymentItem';

export class CreatePaymentSessionRequest {
    'webhook': string;
    'successUrl': string;
    'cancelUrl': string;
    'items': Array<PaymentItem>;
    'clientReferenceId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "webhook",
            "baseName": "webhook",
            "type": "string"
        },
        {
            "name": "successUrl",
            "baseName": "success_url",
            "type": "string"
        },
        {
            "name": "cancelUrl",
            "baseName": "cancel_url",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<PaymentItem>"
        },
        {
            "name": "clientReferenceId",
            "baseName": "client_reference_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreatePaymentSessionRequest.attributeTypeMap;
    }
}

