/**
 * operon-demo-payment-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreatePaymentSession200Response {
    'sessionId': string;
    'url': string;
    'paymentStatus': CreatePaymentSession200Response.PaymentStatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sessionId",
            "baseName": "session_id",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "paymentStatus",
            "baseName": "payment_status",
            "type": "CreatePaymentSession200Response.PaymentStatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return CreatePaymentSession200Response.attributeTypeMap;
    }
}

export namespace CreatePaymentSession200Response {
    export enum PaymentStatusEnum {
        Pending = <any> 'pending',
        Paid = <any> 'paid',
        Cancelled = <any> 'cancelled'
    }
}
