# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: disclosure-detective
language: python
runtimeConfig:
  start:
    - "fastapi run disclosure_detective/main.py"
database:
  hostname: localhost
  port: 5432
  username: postgres
  password: ${PGPASSWORD}
  app_db_name: disclosure_detective
  migrate:
    - alembic upgrade head
telemetry:
  logs:
    logLevel: INFO