# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-ts/main/dbos-config.schema.json

name: dbos-node-toolbox
language: node
runtimeConfig:
  start:
    - node dist/main.js
database:
  migrate:
    - npx knex migrate:latest
telemetry:
  logs:
    logLevel: 'info'