
export type ScheduleRecord = {
  id: string; // UUID as primary key
  task: string; // Task identifier
  start_time: string; // ISO datetime string
  end_time: string; // ISO datetime string
  repeat: string; // Repetition rule
  created_at?: string; // Timestamp (autogenerated)
  updated_at?: string; // Timestamp (autogenerated)
};

export type ResultsRecord = {
  schedule_id: string; // UUID referencing ScheduleRecord
  run_time: string; // ISO datetime string
  result: string; // JSON, HTML, or text stored as a string
};
