
export interface ScheduleRecord {
  id: string; // UUID as primary key
  task: string; // Task identifier (see tasks.ts)
  start_time: string; // ISO datetime string
  end_time: string; // ISO datetime string
  repeat: string; // Repetition rule
  created_at?: string; // Timestamp (autogenerated)
  updated_at?: string; // Timestamp (autogenerated)
};

export interface ScheduleUIRecord extends ScheduleRecord {
  name: string;
}

export interface ResultsRecord {
  schedule_id: string; // UUID referencing ScheduleRecord
  task: string; // Task identifier (see tasks.ts)
  run_time: string; // ISO datetime string
  result: string; // JSON, HTML, or text stored as a string
};

export interface ResultsUIRecord extends ResultsRecord {
  name: string;
}

export type TaskOption = {
  id: string;
  name: string;
};