/* tslint:disable */
/* eslint-disable */
/**
 * social-ts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DoFindUser200ResponseAnyOf } from './DoFindUser200ResponseAnyOf';
import {
    DoFindUser200ResponseAnyOfFromJSON,
    DoFindUser200ResponseAnyOfFromJSONTyped,
    DoFindUser200ResponseAnyOfToJSON,
} from './DoFindUser200ResponseAnyOf';
import type { DoFindUser200ResponseAnyOf1 } from './DoFindUser200ResponseAnyOf1';
import {
    DoFindUser200ResponseAnyOf1FromJSON,
    DoFindUser200ResponseAnyOf1FromJSONTyped,
    DoFindUser200ResponseAnyOf1ToJSON,
} from './DoFindUser200ResponseAnyOf1';

/**
 * 
 * @export
 * @interface DoFindUser200Response
 */
export interface DoFindUser200Response {
    /**
     * 
     * @type {string}
     * @memberof DoFindUser200Response
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof DoFindUser200Response
     */
    uid: string;
    /**
     * 
     * @type {string}
     * @memberof DoFindUser200Response
     */
    name: string;
}

/**
 * Check if a given object implements the DoFindUser200Response interface.
 */
export function instanceOfDoFindUser200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "uid" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function DoFindUser200ResponseFromJSON(json: any): DoFindUser200Response {
    return DoFindUser200ResponseFromJSONTyped(json, false);
}

export function DoFindUser200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoFindUser200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'uid': json['uid'],
        'name': json['name'],
    };
}

export function DoFindUser200ResponseToJSON(value?: DoFindUser200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'uid': value.uid,
        'name': value.name,
    };
}

