/* tslint:disable */
/* eslint-disable */
/**
 * social-ts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DoFindUser200ResponseAnyOf
 */
export interface DoFindUser200ResponseAnyOf {
    /**
     * 
     * @type {string}
     * @memberof DoFindUser200ResponseAnyOf
     */
    message: string;
    /**
     * 
     * @type {any}
     * @memberof DoFindUser200ResponseAnyOf
     */
    uid?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DoFindUser200ResponseAnyOf
     */
    name?: any | null;
}

/**
 * Check if a given object implements the DoFindUser200ResponseAnyOf interface.
 */
export function instanceOfDoFindUser200ResponseAnyOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function DoFindUser200ResponseAnyOfFromJSON(json: any): DoFindUser200ResponseAnyOf {
    return DoFindUser200ResponseAnyOfFromJSONTyped(json, false);
}

export function DoFindUser200ResponseAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoFindUser200ResponseAnyOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'uid': !exists(json, 'uid') ? undefined : json['uid'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function DoFindUser200ResponseAnyOfToJSON(value?: DoFindUser200ResponseAnyOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'uid': value.uid,
        'name': value.name,
    };
}

