/* tslint:disable */
/* eslint-disable */
/**
 * social-ts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DoFindUser200ResponseAnyOf1
 */
export interface DoFindUser200ResponseAnyOf1 {
    /**
     * 
     * @type {string}
     * @memberof DoFindUser200ResponseAnyOf1
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof DoFindUser200ResponseAnyOf1
     */
    uid: string;
    /**
     * 
     * @type {string}
     * @memberof DoFindUser200ResponseAnyOf1
     */
    name: string;
}

/**
 * Check if a given object implements the DoFindUser200ResponseAnyOf1 interface.
 */
export function instanceOfDoFindUser200ResponseAnyOf1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "uid" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function DoFindUser200ResponseAnyOf1FromJSON(json: any): DoFindUser200ResponseAnyOf1 {
    return DoFindUser200ResponseAnyOf1FromJSONTyped(json, false);
}

export function DoFindUser200ResponseAnyOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): DoFindUser200ResponseAnyOf1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'uid': json['uid'],
        'name': json['name'],
    };
}

export function DoFindUser200ResponseAnyOf1ToJSON(value?: DoFindUser200ResponseAnyOf1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'uid': value.uid,
        'name': value.name,
    };
}

