/* tslint:disable */
/* eslint-disable */
/**
 * social-ts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DoKeyDownload200Response
 */
export interface DoKeyDownload200Response {
    /**
     * 
     * @type {string}
     * @memberof DoKeyDownload200Response
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof DoKeyDownload200Response
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof DoKeyDownload200Response
     */
    key: string;
}

/**
 * Check if a given object implements the DoKeyDownload200Response interface.
 */
export function instanceOfDoKeyDownload200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function DoKeyDownload200ResponseFromJSON(json: any): DoKeyDownload200Response {
    return DoKeyDownload200ResponseFromJSONTyped(json, false);
}

export function DoKeyDownload200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoKeyDownload200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'url': json['url'],
        'key': json['key'],
    };
}

export function DoKeyDownload200ResponseToJSON(value?: DoKeyDownload200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'url': value.url,
        'key': value.key,
    };
}

