/* tslint:disable */
/* eslint-disable */
/**
 * social-ts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PresignedPost } from './PresignedPost';
import {
    PresignedPostFromJSON,
    PresignedPostFromJSONTyped,
    PresignedPostToJSON,
} from './PresignedPost';

/**
 * 
 * @export
 * @interface DoStartMediaUpload200Response
 */
export interface DoStartMediaUpload200Response {
    /**
     * 
     * @type {string}
     * @memberof DoStartMediaUpload200Response
     */
    wfHandle: string;
    /**
     * 
     * @type {PresignedPost}
     * @memberof DoStartMediaUpload200Response
     */
    key: PresignedPost;
    /**
     * 
     * @type {string}
     * @memberof DoStartMediaUpload200Response
     */
    file: string;
}

/**
 * Check if a given object implements the DoStartMediaUpload200Response interface.
 */
export function instanceOfDoStartMediaUpload200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "wfHandle" in value;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "file" in value;

    return isInstance;
}

export function DoStartMediaUpload200ResponseFromJSON(json: any): DoStartMediaUpload200Response {
    return DoStartMediaUpload200ResponseFromJSONTyped(json, false);
}

export function DoStartMediaUpload200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoStartMediaUpload200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'wfHandle': json['wfHandle'],
        'key': PresignedPostFromJSON(json['key']),
        'file': json['file'],
    };
}

export function DoStartMediaUpload200ResponseToJSON(value?: DoStartMediaUpload200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'wfHandle': value.wfHandle,
        'key': PresignedPostToJSON(value.key),
        'file': value.file,
    };
}

