/* tslint:disable */
/* eslint-disable */
/**
 * social-ts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Post } from './Post';
import {
    PostFromJSON,
    PostFromJSONTyped,
    PostToJSON,
} from './Post';

/**
 * 
 * @export
 * @interface GetPost200ResponseAnyOf
 */
export interface GetPost200ResponseAnyOf {
    /**
     * 
     * @type {string}
     * @memberof GetPost200ResponseAnyOf
     */
    message: string;
    /**
     * 
     * @type {Post}
     * @memberof GetPost200ResponseAnyOf
     */
    post: Post;
}

/**
 * Check if a given object implements the GetPost200ResponseAnyOf interface.
 */
export function instanceOfGetPost200ResponseAnyOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "post" in value;

    return isInstance;
}

export function GetPost200ResponseAnyOfFromJSON(json: any): GetPost200ResponseAnyOf {
    return GetPost200ResponseAnyOfFromJSONTyped(json, false);
}

export function GetPost200ResponseAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPost200ResponseAnyOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'post': PostFromJSON(json['post']),
    };
}

export function GetPost200ResponseAnyOfToJSON(value?: GetPost200ResponseAnyOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'post': PostToJSON(value.post),
    };
}

