/* tslint:disable */
/* eslint-disable */
/**
 * social-ts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DoKeyDownload200Response } from './DoKeyDownload200Response';
import {
    DoKeyDownload200ResponseFromJSON,
    DoKeyDownload200ResponseFromJSONTyped,
    DoKeyDownload200ResponseToJSON,
} from './DoKeyDownload200Response';
import type { GetProfilePhoto200ResponseAnyOf } from './GetProfilePhoto200ResponseAnyOf';
import {
    GetProfilePhoto200ResponseAnyOfFromJSON,
    GetProfilePhoto200ResponseAnyOfFromJSONTyped,
    GetProfilePhoto200ResponseAnyOfToJSON,
} from './GetProfilePhoto200ResponseAnyOf';

/**
 * 
 * @export
 * @interface GetProfilePhoto200Response
 */
export interface GetProfilePhoto200Response {
    /**
     * 
     * @type {string}
     * @memberof GetProfilePhoto200Response
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof GetProfilePhoto200Response
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof GetProfilePhoto200Response
     */
    key: string;
}

/**
 * Check if a given object implements the GetProfilePhoto200Response interface.
 */
export function instanceOfGetProfilePhoto200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function GetProfilePhoto200ResponseFromJSON(json: any): GetProfilePhoto200Response {
    return GetProfilePhoto200ResponseFromJSONTyped(json, false);
}

export function GetProfilePhoto200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProfilePhoto200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'url': json['url'],
        'key': json['key'],
    };
}

export function GetProfilePhoto200ResponseToJSON(value?: GetProfilePhoto200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'url': value.url,
        'key': value.key,
    };
}

