/* tslint:disable */
/* eslint-disable */
/**
 * social-ts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RecvType } from './RecvType';
import {
    RecvTypeFromJSON,
    RecvTypeFromJSONTyped,
    RecvTypeToJSON,
} from './RecvType';

/**
 * 
 * @export
 * @interface ReceiveTimeline200ResponseTimelineInner
 */
export interface ReceiveTimeline200ResponseTimelineInner {
    /**
     * 
     * @type {string}
     * @memberof ReceiveTimeline200ResponseTimelineInner
     */
    postId: string;
    /**
     * 
     * @type {string}
     * @memberof ReceiveTimeline200ResponseTimelineInner
     */
    fromUserId: string;
    /**
     * 
     * @type {boolean}
     * @memberof ReceiveTimeline200ResponseTimelineInner
     */
    unread: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ReceiveTimeline200ResponseTimelineInner
     */
    sendDate: Date;
    /**
     * 
     * @type {RecvType}
     * @memberof ReceiveTimeline200ResponseTimelineInner
     */
    recvType: RecvType;
    /**
     * 
     * @type {string}
     * @memberof ReceiveTimeline200ResponseTimelineInner
     */
    postText: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReceiveTimeline200ResponseTimelineInner
     */
    postMentions: Array<string>;
}

/**
 * Check if a given object implements the ReceiveTimeline200ResponseTimelineInner interface.
 */
export function instanceOfReceiveTimeline200ResponseTimelineInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "postId" in value;
    isInstance = isInstance && "fromUserId" in value;
    isInstance = isInstance && "unread" in value;
    isInstance = isInstance && "sendDate" in value;
    isInstance = isInstance && "recvType" in value;
    isInstance = isInstance && "postText" in value;
    isInstance = isInstance && "postMentions" in value;

    return isInstance;
}

export function ReceiveTimeline200ResponseTimelineInnerFromJSON(json: any): ReceiveTimeline200ResponseTimelineInner {
    return ReceiveTimeline200ResponseTimelineInnerFromJSONTyped(json, false);
}

export function ReceiveTimeline200ResponseTimelineInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiveTimeline200ResponseTimelineInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'postId': json['postId'],
        'fromUserId': json['fromUserId'],
        'unread': json['unread'],
        'sendDate': (new Date(json['sendDate'])),
        'recvType': RecvTypeFromJSON(json['recvType']),
        'postText': json['postText'],
        'postMentions': json['postMentions'],
    };
}

export function ReceiveTimeline200ResponseTimelineInnerToJSON(value?: ReceiveTimeline200ResponseTimelineInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'postId': value.postId,
        'fromUserId': value.fromUserId,
        'unread': value.unread,
        'sendDate': (value.sendDate.toISOString()),
        'recvType': RecvTypeToJSON(value.recvType),
        'postText': value.postText,
        'postMentions': value.postMentions,
    };
}

