/* tslint:disable */
/* eslint-disable */
/**
 * bank-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAccountFuncRequest
 */
export interface CreateAccountFuncRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateAccountFuncRequest
     */
    ownerName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAccountFuncRequest
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof CreateAccountFuncRequest
     */
    balance?: number;
}

/**
 * Check if a given object implements the CreateAccountFuncRequest interface.
 */
export function instanceOfCreateAccountFuncRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ownerName" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function CreateAccountFuncRequestFromJSON(json: any): CreateAccountFuncRequest {
    return CreateAccountFuncRequestFromJSONTyped(json, false);
}

export function CreateAccountFuncRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAccountFuncRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ownerName': json['ownerName'],
        'type': json['type'],
        'balance': !exists(json, 'balance') ? undefined : json['balance'],
    };
}

export function CreateAccountFuncRequestToJSON(value?: CreateAccountFuncRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ownerName': value.ownerName,
        'type': value.type,
        'balance': value.balance,
    };
}

