/* tslint:disable */
/* eslint-disable */
/**
 * bank-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListAccountsFunc200ResponseInner
 */
export interface ListAccountsFunc200ResponseInner {
    /**
     * bigint
     * @type {number}
     * @memberof ListAccountsFunc200ResponseInner
     */
    accountId: number;
    /**
     * 
     * @type {string}
     * @memberof ListAccountsFunc200ResponseInner
     */
    ownerName: string;
    /**
     * 
     * @type {string}
     * @memberof ListAccountsFunc200ResponseInner
     */
    type: string;
    /**
     * bigint
     * @type {number}
     * @memberof ListAccountsFunc200ResponseInner
     */
    balance: number;
}

/**
 * Check if a given object implements the ListAccountsFunc200ResponseInner interface.
 */
export function instanceOfListAccountsFunc200ResponseInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountId" in value;
    isInstance = isInstance && "ownerName" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "balance" in value;

    return isInstance;
}

export function ListAccountsFunc200ResponseInnerFromJSON(json: any): ListAccountsFunc200ResponseInner {
    return ListAccountsFunc200ResponseInnerFromJSONTyped(json, false);
}

export function ListAccountsFunc200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAccountsFunc200ResponseInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'ownerName': json['ownerName'],
        'type': json['type'],
        'balance': json['balance'],
    };
}

export function ListAccountsFunc200ResponseInnerToJSON(value?: ListAccountsFunc200ResponseInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountId': value.accountId,
        'ownerName': value.ownerName,
        'type': value.type,
        'balance': value.balance,
    };
}

