/* tslint:disable */
/* eslint-disable */
/**
 * bank-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListTxnForAccountFunc200ResponseInner
 */
export interface ListTxnForAccountFunc200ResponseInner {
    /**
     * bigint
     * @type {number}
     * @memberof ListTxnForAccountFunc200ResponseInner
     */
    txnId: number;
    /**
     * bigint
     * @type {number}
     * @memberof ListTxnForAccountFunc200ResponseInner
     */
    fromAccountId: number;
    /**
     * 
     * @type {string}
     * @memberof ListTxnForAccountFunc200ResponseInner
     */
    fromLocation: string;
    /**
     * bigint
     * @type {number}
     * @memberof ListTxnForAccountFunc200ResponseInner
     */
    toAccountId: number;
    /**
     * 
     * @type {string}
     * @memberof ListTxnForAccountFunc200ResponseInner
     */
    toLocation: string;
    /**
     * 
     * @type {number}
     * @memberof ListTxnForAccountFunc200ResponseInner
     */
    amount: number;
    /**
     * 
     * @type {Date}
     * @memberof ListTxnForAccountFunc200ResponseInner
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the ListTxnForAccountFunc200ResponseInner interface.
 */
export function instanceOfListTxnForAccountFunc200ResponseInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "txnId" in value;
    isInstance = isInstance && "fromAccountId" in value;
    isInstance = isInstance && "fromLocation" in value;
    isInstance = isInstance && "toAccountId" in value;
    isInstance = isInstance && "toLocation" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "timestamp" in value;

    return isInstance;
}

export function ListTxnForAccountFunc200ResponseInnerFromJSON(json: any): ListTxnForAccountFunc200ResponseInner {
    return ListTxnForAccountFunc200ResponseInnerFromJSONTyped(json, false);
}

export function ListTxnForAccountFunc200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTxnForAccountFunc200ResponseInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'txnId': json['txnId'],
        'fromAccountId': json['fromAccountId'],
        'fromLocation': json['fromLocation'],
        'toAccountId': json['toAccountId'],
        'toLocation': json['toLocation'],
        'amount': json['amount'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function ListTxnForAccountFunc200ResponseInnerToJSON(value?: ListTxnForAccountFunc200ResponseInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'txnId': value.txnId,
        'fromAccountId': value.fromAccountId,
        'fromLocation': value.fromLocation,
        'toAccountId': value.toAccountId,
        'toLocation': value.toLocation,
        'amount': value.amount,
        'timestamp': (value.timestamp.toISOString()),
    };
}

