name: stock-prices
language: python
runtimeConfig:
  start:
    - python3 stock_prices/main.py & streamlit run stock_prices/streamlit.py --server.port 8000 --server.enableCORS=false --server.enableXsrfProtection=false --browser.gatherUsageStats=false
database_url: "postgresql://postgres:${PGPASSWORD}@localhost:5432/stock_prices"
database:
  migrate:
    - alembic upgrade head
env:
  TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
  TWILIO_PHONE_NUMBER: "${TWILIO_PHONE_NUMBER}"
  MY_PHONE_NUMBER: "${MY_PHONE_NUMBER}"
