# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: ai-storyteller
language: python
runtimeConfig:
  start:
    - "fastapi run ./main.py"
database:
  hostname: localhost
  port: 5432
  username: postgres
  password: ${PGPASSWORD}
  app_db_name: ai_storyteller
  migrate:
    - echo 'No migrations specified'
telemetry:
  logs:
    logLevel: INFO
env:
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}