# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact/main/dbos-config.schema.json
language: node
name: dbos-nest-starter
database:
  migrate:
    - npm run db:setup
runtimeConfig:
  start:
    - npx nest start
