org.slf4j.simpleLogger.defaultLogLevel=info

org.slf4j.simpleLogger.log.com.zaxxer.hikari=warn
org.slf4j.simpleLogger.log.dev.dbos.transact=info
org.slf4j.simpleLogger.log.dev.dbos.transact.migrations=warn