"""greeting_guestbook

Revision ID: 78f4ffbf4e4a
Revises: c6b516e182b2
Create Date: 2024-08-29 12:32:37.867280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f4ffbf4e4a'
down_revision: Union[str, None] = 'c6b516e182b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('greetings',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True)
    )
    op.drop_table('dbos_hello')
    op.drop_table('dbos_greetings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbos_greetings',
    sa.Column('greeting_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('greeting_note_content', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('dbos_hello',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('greet_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='dbos_hello_pkey')
    )
    op.drop_table('greetings')
    # ### end Alembic commands ###
