spring.application.name=widget-store

spring.datasource.url=jdbc:postgresql://localhost:5432/widget_store_java
spring.datasource.username=postgres
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
