"""progress_remaining

Revision ID: ebae15d77b39
Revises: 45dd7d40a046
Create Date: 2024-08-30 12:46:56.053152

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebae15d77b39"
down_revision: Union[str, None] = "45dd7d40a046"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "progress_remaining", sa.Integer(), server_default="10", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "progress_remaining")
    # ### end Alembic commands ###
