# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: scheduled-reminders
language: python
runtimeConfig:
  start:
    - "fastapi run scheduled_reminders/main.py"
database:
  hostname: localhost
  port: 5432
  username: postgres
  password: ${PGPASSWORD}
  app_db_name: scheduled_reminders
  migrate:
    - echo "no migrations"
telemetry:
  logs:
    logLevel: INFO
env:
  SENDGRID_API_KEY: ${SENDGRID_API_KEY}
  SENDGRID_FROM_EMAIL: ${SENDGRID_FROM_EMAIL}