[project]
name = "scheduled-reminders"
version = "0.1.0"
dependencies = [
    "dbos>=0.7.0a9",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
