# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: stock-ticker
language: python
runtimeConfig:
  start:
    - fastapi run
database:
  hostname: localhost
  port: 5432
  username: postgres
  password: ${PGPASSWORD}
  app_db_name: stock_ticker
  migrate:
    - echo "No migrations"
telemetry:
  logs:
    logLevel: INFO