# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: llamabot
language: python
runtimeConfig:
  start:
    - "fastapi run llamabot/main.py"
database_url: ${DBOS_DATABASE_URL}
database:
  migrate:
    - python3 migrations/migrate.py
env:
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
  SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
