# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: llamabot
language: python
runtimeConfig:
  start:
    - python3 llamabot/main.py
database_url: ${DBOS_DATABASE_URL}
database:
  migrate:
    - python3 migrations/migrate.py
