/* tslint:disable */
/* eslint-disable */
/**
 * social-ts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DoFollowRequest
 */
export interface DoFollowRequest {
    /**
     * 
     * @type {string}
     * @memberof DoFollowRequest
     */
    followUid: string;
}

/**
 * Check if a given object implements the DoFollowRequest interface.
 */
export function instanceOfDoFollowRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "followUid" in value;

    return isInstance;
}

export function DoFollowRequestFromJSON(json: any): DoFollowRequest {
    return DoFollowRequestFromJSONTyped(json, false);
}

export function DoFollowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoFollowRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'followUid': json['followUid'],
    };
}

export function DoFollowRequestToJSON(value?: DoFollowRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'followUid': value.followUid,
    };
}

