/* tslint:disable */
/* eslint-disable */
/**
 * social-ts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DoLogin200Response
 */
export interface DoLogin200Response {
    /**
     * 
     * @type {string}
     * @memberof DoLogin200Response
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof DoLogin200Response
     */
    id: string;
}

/**
 * Check if a given object implements the DoLogin200Response interface.
 */
export function instanceOfDoLogin200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function DoLogin200ResponseFromJSON(json: any): DoLogin200Response {
    return DoLogin200ResponseFromJSONTyped(json, false);
}

export function DoLogin200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoLogin200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'id': json['id'],
    };
}

export function DoLogin200ResponseToJSON(value?: DoLogin200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'id': value.id,
    };
}

