/* tslint:disable */
/* eslint-disable */
/**
 * social-ts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DoRegisterRequest
 */
export interface DoRegisterRequest {
    /**
     * 
     * @type {string}
     * @memberof DoRegisterRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof DoRegisterRequest
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof DoRegisterRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof DoRegisterRequest
     */
    password: string;
}

/**
 * Check if a given object implements the DoRegisterRequest interface.
 */
export function instanceOfDoRegisterRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "firstName" in value;
    isInstance = isInstance && "lastName" in value;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function DoRegisterRequestFromJSON(json: any): DoRegisterRequest {
    return DoRegisterRequestFromJSONTyped(json, false);
}

export function DoRegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoRegisterRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'username': json['username'],
        'password': json['password'],
    };
}

export function DoRegisterRequestToJSON(value?: DoRegisterRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstName': value.firstName,
        'lastName': value.lastName,
        'username': value.username,
        'password': value.password,
    };
}

