/* tslint:disable */
/* eslint-disable */
/**
 * social-ts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPost200ResponseAnyOf1
 */
export interface GetPost200ResponseAnyOf1 {
    /**
     * 
     * @type {string}
     * @memberof GetPost200ResponseAnyOf1
     */
    message: string;
    /**
     * 
     * @type {any}
     * @memberof GetPost200ResponseAnyOf1
     */
    post?: any | null;
}

/**
 * Check if a given object implements the GetPost200ResponseAnyOf1 interface.
 */
export function instanceOfGetPost200ResponseAnyOf1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function GetPost200ResponseAnyOf1FromJSON(json: any): GetPost200ResponseAnyOf1 {
    return GetPost200ResponseAnyOf1FromJSONTyped(json, false);
}

export function GetPost200ResponseAnyOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPost200ResponseAnyOf1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'post': !exists(json, 'post') ? undefined : json['post'],
    };
}

export function GetPost200ResponseAnyOf1ToJSON(value?: GetPost200ResponseAnyOf1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'post': value.post,
    };
}

