/* tslint:disable */
/* eslint-disable */
/**
 * social-ts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProfilePhoto200ResponseAnyOf
 */
export interface GetProfilePhoto200ResponseAnyOf {
    /**
     * 
     * @type {any}
     * @memberof GetProfilePhoto200ResponseAnyOf
     */
    message?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetProfilePhoto200ResponseAnyOf
     */
    url?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetProfilePhoto200ResponseAnyOf
     */
    key?: any | null;
}

/**
 * Check if a given object implements the GetProfilePhoto200ResponseAnyOf interface.
 */
export function instanceOfGetProfilePhoto200ResponseAnyOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetProfilePhoto200ResponseAnyOfFromJSON(json: any): GetProfilePhoto200ResponseAnyOf {
    return GetProfilePhoto200ResponseAnyOfFromJSONTyped(json, false);
}

export function GetProfilePhoto200ResponseAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProfilePhoto200ResponseAnyOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'key': !exists(json, 'key') ? undefined : json['key'],
    };
}

export function GetProfilePhoto200ResponseAnyOfToJSON(value?: GetProfilePhoto200ResponseAnyOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'url': value.url,
        'key': value.key,
    };
}

