/* tslint:disable */
/* eslint-disable */
/**
 * social-ts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Hello200Response
 */
export interface Hello200Response {
    /**
     * 
     * @type {string}
     * @memberof Hello200Response
     */
    message: string;
}

/**
 * Check if a given object implements the Hello200Response interface.
 */
export function instanceOfHello200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function Hello200ResponseFromJSON(json: any): Hello200Response {
    return Hello200ResponseFromJSONTyped(json, false);
}

export function Hello200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Hello200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function Hello200ResponseToJSON(value?: Hello200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

