/* tslint:disable */
/* eslint-disable */
/**
 * social-ts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReceiveTimeline200ResponseTimelineInner } from './ReceiveTimeline200ResponseTimelineInner';
import {
    ReceiveTimeline200ResponseTimelineInnerFromJSON,
    ReceiveTimeline200ResponseTimelineInnerFromJSONTyped,
    ReceiveTimeline200ResponseTimelineInnerToJSON,
} from './ReceiveTimeline200ResponseTimelineInner';

/**
 * 
 * @export
 * @interface ReceiveTimeline200Response
 */
export interface ReceiveTimeline200Response {
    /**
     * 
     * @type {string}
     * @memberof ReceiveTimeline200Response
     */
    message: string;
    /**
     * 
     * @type {Array<ReceiveTimeline200ResponseTimelineInner>}
     * @memberof ReceiveTimeline200Response
     */
    timeline: Array<ReceiveTimeline200ResponseTimelineInner>;
}

/**
 * Check if a given object implements the ReceiveTimeline200Response interface.
 */
export function instanceOfReceiveTimeline200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "timeline" in value;

    return isInstance;
}

export function ReceiveTimeline200ResponseFromJSON(json: any): ReceiveTimeline200Response {
    return ReceiveTimeline200ResponseFromJSONTyped(json, false);
}

export function ReceiveTimeline200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiveTimeline200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'timeline': ((json['timeline'] as Array<any>).map(ReceiveTimeline200ResponseTimelineInnerFromJSON)),
    };
}

export function ReceiveTimeline200ResponseToJSON(value?: ReceiveTimeline200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'timeline': ((value.timeline as Array<any>).map(ReceiveTimeline200ResponseTimelineInnerToJSON)),
    };
}

