/* tslint:disable */
/* eslint-disable */
/**
 * social-ts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RecvType = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type RecvType = typeof RecvType[keyof typeof RecvType];


export function RecvTypeFromJSON(json: any): RecvType {
    return RecvTypeFromJSONTyped(json, false);
}

export function RecvTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecvType {
    return json as RecvType;
}

export function RecvTypeToJSON(value?: RecvType | null): any {
    return value as any;
}

