/* tslint:disable */
/* eslint-disable */
/**
 * social-ts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SendType = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type SendType = typeof SendType[keyof typeof SendType];


export function SendTypeFromJSON(json: any): SendType {
    return SendTypeFromJSONTyped(json, false);
}

export function SendTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendType {
    return json as SendType;
}

export function SendTypeToJSON(value?: SendType | null): any {
    return value as any;
}

