/* tslint:disable */
/* eslint-disable */
/**
 * social-ts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserLogin
 */
export interface UserLogin {
    /**
     * 
     * @type {string}
     * @memberof UserLogin
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserLogin
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof UserLogin
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof UserLogin
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof UserLogin
     */
    passwordHash: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserLogin
     */
    active: boolean;
}

/**
 * Check if a given object implements the UserLogin interface.
 */
export function instanceOfUserLogin(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "firstName" in value;
    isInstance = isInstance && "lastName" in value;
    isInstance = isInstance && "userName" in value;
    isInstance = isInstance && "passwordHash" in value;
    isInstance = isInstance && "active" in value;

    return isInstance;
}

export function UserLoginFromJSON(json: any): UserLogin {
    return UserLoginFromJSONTyped(json, false);
}

export function UserLoginFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLogin {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'userName': json['user_name'],
        'passwordHash': json['password_hash'],
        'active': json['active'],
    };
}

export function UserLoginToJSON(value?: UserLogin | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'first_name': value.firstName,
        'last_name': value.lastName,
        'user_name': value.userName,
        'password_hash': value.passwordHash,
        'active': value.active,
    };
}

