database:
  hostname: 'localhost'
  port: 5432
  username: 'postgres'
  password: ${PGPASSWORD}
  user_database: 'payment'
  system_database: 'payment_systemdb'
  connectionTimeoutMillis: 3000
  user_dbclient: 'knex'
  ssl_ca: us-east-1-bundle.pem
  migrate: ['migrate:latest']
  rollback: ['migrate:rollback']
runtimeConfig:
  port: 8086
application:
  frontend_host: 'http://localhost:8000'


