# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-sdk/main/dbos-config.schema.json

database:
  hostname: 'localhost'
  port: 5432
  username: 'postgres'
  password: ${PGPASSWORD}
  app_db_name: 'payment'
  connectionTimeoutMillis: 3000
  app_db_client: 'knex'
  migrate: ['npx knex migrate:latest']
  rollback: ['npx knex migrate:rollback']
runtimeConfig:
  port: 8086
application:
  frontend_host: 'http://localhost:8086'
  # For DBOS Cloud:
  frontend_host: 'https://<username>-<app-name>.cloud.dbos.dev'
