# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact/main/dbos-config.schema.json

database:
  hostname: 'localhost'
  port: 5432
  username: 'postgres'
  password: ${PGPASSWORD}
  app_db_name: 'hello_guestbook'
  connectionTimeoutMillis: 3000
  app_db_client: 'knex'
  migrate: ['npx knex migrate:latest']
  rollback: ['npx knex migrate:rollback']
env:
  GUESTBOOK_KEY: 'f1fda8b7-9f35-45c7-bee8-155f7ec2c130' #visit https://demo-guestbook.cloud.dbos.dev/key to create a key

