database:
  hostname: 'localhost'
  port: 5432
  username: 'bank'
  connectionTimeoutMillis: 3000
  app_db_name: 'bank'
  password: ${PGPASSWORD}
  app_db_client: "prisma"
runtimeConfig:
  port: 8081
application:
  bankname: "testbank - ${BANK_SCHEMA}"
  bankport: '8091'
  bankschema: ${BANK_SCHEMA}