database:
  hostname: 'localhost'
  port: 5432
  username: 'bank'
  connectionTimeoutMillis: 3000
  user_database: 'bank'
  password: ${PGPASSWORD}
  system_database: 'dbos_bank_systemdb'
  user_dbclient: "prisma"
telemetry:
  logs:
    logLevel: 'info'
    addContextMetadata: true
    silent: false
  traces:
    enabled: true
    endpoint: 'http://localhost:4318/v1/traces' # Jaeger tracing.
runtimeConfig:
  port: 8081
application:
  bankname: "DBOS Bank - ${BANK_SCHEMA}"
  bankport: '8081'
  bankschema: ${BANK_SCHEMA}
