database:
  hostname: 'localhost'
  port: 5432
  username: 'bank'
  connectionTimeoutMillis: 3000
  user_database: 'bank'
  password: ${PGPASSWORD}
  system_database: 'dbos_bank_test_systemdb'
  user_dbclient: "prisma"
telemetry:
  logs:
    logLevel: 'debug'
    addContextMetadata: true
    silent: false
  traces:
    enabled: false
runtimeConfig:
  port: 8081
application:
  bankname: "testbank - ${BANK_SCHEMA}"
  bankport: '8091'
  bankschema: ${BANK_SCHEMA}