database:
  hostname: 'localhost'
  port: 5432
  username: 'bank'
  connectionTimeoutMillis: 3000
  user_database: 'bank'
  password: ${PGPASSWORD}
  system_database: 'operon_bank_test_systemdb'
  user_dbclient: "prisma"
telemetry:
  logs:
    logLevel: 'debug'
    addContextMetadata: true
    silent: false
  traces:
    enabled: true
    endpoint: 'http://localhost:4318/v1/traces' # Jaeger tracing.
localRuntimeConfig:
  port: 8081
application:
  bankname: 'localbank'
  bankport: '8081'
