database:
  hostname: 'localhost'
  port: 5432
  username: 'bank'
  connectionTimeoutMillis: 3000
  user_database: 'bank'
  system_database: 'operon_bank_systemdb'
telemetryExporters:
  - 'ConsoleExporter'
  - 'JaegerExporter'
