# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: empyrical-evidences
language: python
runtimeConfig:
  start:
    - "fastapi run empyrical/main.py"
database:
  hostname: localhost
  port: 5432
  username: postgres
  password: ${PGPASSWORD}
  app_db_name: empyrical_evidences
  migrate:
    - alembic upgrade head
    - python3 -m migrations.migrate
telemetry:
  logs:
    logLevel: INFO
env:
  TOGETHER_API_KEY: ${TOGETHER_API_KEY}
