database:
  hostname: 'localhost'
  port: 5432
  username: 'postgres'
  password: ${PGPASSWORD}
  user_database: 'hello'
  system_database: 'hello_systemdb'
  connectionTimeoutMillis: 3000
  user_dbclient: 'knex'
