database:
  hostname: 'localhost'
  port: 5432
  username: 'postgres'
  password: ${PGPASSWORD}
  app_db_name: 'hello'
  user_database: 'hello'
  connectionTimeoutMillis: 3000
  app_db_client: 'knex'
  user_dbclient: 'knex'