database:
  hostname: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  username: ${POSTGRES_USERNAME}
  password: ${POSTGRES_PASSWORD}
  user_database: ${POSTGRES_DATABASE}
  system_database: 'opsys'
  connectionTimeoutMillis: 3000
  user_dbclient: 'typeorm'
telemetry:
  logs:
    logLevel: 'debug'
    addContextMetadata: true
    silent: false
  traces:
    enabled: false
runtimeConfig:
  port: 3000
application:
  aws_s3_region: ${AWS_REGION}
  aws_s3_bucket: ${S3_BUCKET_NAME}
  aws_s3_access_key: ${AWS_ACCESS_KEY}
  aws_s3_access_secret: ${AWS_SECRET_ACCESS_KEY}

