name: CI for Java DBOS Starter

on:
  push:
    branches: [ "main" ]
    paths:
      - 'java/dbos-starter/**'
      - '.github/workflows/java-dbos-starter.yml'
  pull_request:
    types:
      - ready_for_review
      - opened
      - reopened
      - synchronize
    paths:
      - 'java/dbos-starter/**'
      - '.github/workflows/java-dbos-starter.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        working-directory: java/dbos-starter/
        run: ./gradlew test
